import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ClientToast from "./components/ClientToast";

import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "cinebooking",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="modal">{modal}</div>
        <ClientToast />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
